name: Deploy via SSH # (1) Title of the action

on:
  push:
    branches:
      - main # (2) Name of the branch where the action should run

jobs:
  deploy:
    name: Deploy to SSH Server # (3) Title of the job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: login.toolforge.org
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          request_pty: true
          script_stop: true
          # (4) Actual command(s) to run
          script: |
            become ncc
            toolforge-jobs run update --image mariadb --command "$HOME/move.sh"
